### ISSUE TITLE
pivotnacci support win10？

### ISSUE THREAD

**Issue by cug3r** [blackarrowsec/pivotnacci#1]
![image](https://user-images.githubusercontent.com/796046/81272029-79fb9a80-907f-11ea-91ab-1f9a5d186ca6.png)

**Comment by zer1t0** [comment]
Hi, could you provide more details about the issue? (I'm sorry, but I don't understand the error message)

**Comment by cug3r** [comment]
> Hi, could you provide more details about the issue? (I'm sorry, but I don't understand the error message)

well,those chinese words mean:Not an internal or external command, nor a runnable program
Or batch file.
I installed pivotnacci on Win10 with Python3.7
Does pivotnacci support Win10 ?

**Comment by zer1t0** [comment]
Thank you. Yes, windows 10 is supported, however, it seems that windows doesn't handle properly the installation with `pip` (more info in #2).

In this case you can properly run it by installing it from this repository: 
```
git clone https://github.com/blackarrowsec/pivotnacci.git
cd pivotnacci\
pip install -r requirements.txt
python .\pivotnacci -h
```
