### ISSUE TITLE
can't run in cmd on windows after successfully installed pivotnacci with pip 

### ISSUE THREAD

**Issue by Mr-xn** [blackarrowsec/pivotnacci#2]
```
C:\Users\test>pip install pivotnacci
Collecting pivotnacci
  Downloading pivotnacci-0.0.1-py3-none-any.whl (19 kB)
Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
Collecting construct
  Downloading construct-2.10.56.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 27 kB/s
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
Could not build wheels for requests, since package 'wheel' is not installed.
Could not build wheels for construct, since package 'wheel' is not installed.
Could not build wheels for chardet, since package 'wheel' is not installed.
Could not build wheels for certifi, since package 'wheel' is not installed.
Could not build wheels for urllib3, since package 'wheel' is not installed.
Could not build wheels for idna, since package 'wheel' is not installed.
Installing collected packages: construct, pivotnacci
    Running setup.py install for construct ... done
Successfully installed construct-2.10.56 pivotnacci-0.0.1

C:\Users\test>pivotnacci
'pivotnacci' Not an internal or external command, nor a runnable program
Or batch file.

C:\Users\test>pip list
Package           Version
----------------- ----------
.......................
pip               20.1
pip-review        1.0
pivotnacci        0.0.1
.......................
you-get           0.4.1355

C:\Users\test>you-get
usage: you-get [OPTION]... URL...

A tiny downloader that scrapes the web

optional arguments:
  -V, --version         Print version and exit
  -h, --help            Print this help message and exit

Dry-run options:
  (no actual downloading)
```
but can run  `you-get` which installed whith `pip` too

**Comment by Mr-xn** [comment]
### installed wheel and reinstall pivotnacci was the same error
```
C:\Users\test>python -m pip install wheel -i https://mirrors.aliyun.com/pypi/simple/
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting wheel
  Downloading https://mirrors.aliyun.com/pypi/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2

C:\Users\test>pip install pivotnacci
Requirement already satisfied: pivotnacci in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (0.0.1)
Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)

C:\Users\test>pivotnacci
'pivotnacci' Not an internal or external command, nor a runnable program
Or batch file.

C:\Users\test>pip uninstall pivotnacci
Found existing installation: pivotnacci 0.0.1
Uninstalling pivotnacci-0.0.1:
  Would remove:
    c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnacci-0.0.1.dist-info\*
    c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnaccilib\*
    c:\users\test\appdata\local\programs\python\python37\scripts\pivotnacci
Proceed (y/n)? y
  Successfully uninstalled pivotnacci-0.0.1

C:\Users\test>pip install pivotnacci
Collecting pivotnacci
  Using cached pivotnacci-0.0.1-py3-none-any.whl (19 kB)
Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
Installing collected packages: pivotnacci
Successfully installed pivotnacci-0.0.1

C:\Users\test>pivotnacci
'pivotnacci' Not an internal or external command, nor a runnable program
Or batch file.
```

**Comment by Mr-xn** [comment]
> ### installed wheel and reinstall pivotnacci was the same error
> ```
> C:\Users\test>python -m pip install wheel -i https://mirrors.aliyun.com/pypi/simple/
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> Collecting wheel
>   Downloading https://mirrors.aliyun.com/pypi/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl (26 kB)
> Installing collected packages: wheel
> Successfully installed wheel-0.34.2
> 
> C:\Users\test>pip install pivotnacci
> Requirement already satisfied: pivotnacci in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (0.0.1)
> Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
> Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
> Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
> 
> C:\Users\test>pivotnacci
> 'pivotnacci' Not an internal or external command, nor a runnable program
> Or batch file.
> 
> C:\Users\test>pip uninstall pivotnacci
> Found existing installation: pivotnacci 0.0.1
> Uninstalling pivotnacci-0.0.1:
>   Would remove:
>     c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnacci-0.0.1.dist-info\*
>     c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnaccilib\*
>     c:\users\test\appdata\local\programs\python\python37\scripts\pivotnacci
> Proceed (y/n)? y
>   Successfully uninstalled pivotnacci-0.0.1
> 
> C:\Users\test>pip install pivotnacci
> Collecting pivotnacci
>   Using cached pivotnacci-0.0.1-py3-none-any.whl (19 kB)
> Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
> Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
> Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
> Installing collected packages: pivotnacci
> Successfully installed pivotnacci-0.0.1
> 
> C:\Users\test>pivotnacci
> 'pivotnacci' Not an internal or external command, nor a runnable program
> Or batch file.
> ```

from this article 👍 [fix-pip-is-not-recognized-as-an-internal-or-external-command](https://appuals.com/fix-pip-is-not-recognized-as-an-internal-or-external-command/)
perhaps the error was C:\Users\test\AppData\Local\Programs\Python\Python37\Scripts\pivotnacci not pivotnacci.exe as you-get.exe ，if you upgreade pivotnacci.exe to pip source it wil good work.
thank you .

**Comment by Mr-xn** [comment]
> > ### installed wheel and reinstall pivotnacci was the same error
> > ```
> > C:\Users\test>python -m pip install wheel -i https://mirrors.aliyun.com/pypi/simple/
> > Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> > Collecting wheel
> >   Downloading https://mirrors.aliyun.com/pypi/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl (26 kB)
> > Installing collected packages: wheel
> > Successfully installed wheel-0.34.2
> > 
> > C:\Users\test>pip install pivotnacci
> > Requirement already satisfied: pivotnacci in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (0.0.1)
> > Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
> > Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
> > Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
> > Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
> > Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
> > Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
> > 
> > C:\Users\test>pivotnacci
> > 'pivotnacci' Not an internal or external command, nor a runnable program
> > Or batch file.
> > 
> > C:\Users\test>pip uninstall pivotnacci
> > Found existing installation: pivotnacci 0.0.1
> > Uninstalling pivotnacci-0.0.1:
> >   Would remove:
> >     c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnacci-0.0.1.dist-info\*
> >     c:\users\test\appdata\local\programs\python\python37\lib\site-packages\pivotnaccilib\*
> >     c:\users\test\appdata\local\programs\python\python37\scripts\pivotnacci
> > Proceed (y/n)? y
> >   Successfully uninstalled pivotnacci-0.0.1
> > 
> > C:\Users\test>pip install pivotnacci
> > Collecting pivotnacci
> >   Using cached pivotnacci-0.0.1-py3-none-any.whl (19 kB)
> > Requirement already satisfied: construct in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.10.56)
> > Requirement already satisfied: requests in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from pivotnacci) (2.22.0)
> > Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (3.0.4)
> > Requirement already satisfied: idna<2.9,>=2.5 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2.8)
> > Requirement already satisfied: certifi>=2017.4.17 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (2019.11.28)
> > Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\test\appdata\local\programs\python\python37\lib\site-packages (from requests->pivotnacci) (1.25.7)
> > Installing collected packages: pivotnacci
> > Successfully installed pivotnacci-0.0.1
> > 
> > C:\Users\test>pivotnacci
> > 'pivotnacci' Not an internal or external command, nor a runnable program
> > Or batch file.
> > ```
> 
> from this article 👍 [fix-pip-is-not-recognized-as-an-internal-or-external-command](https://appuals.com/fix-pip-is-not-recognized-as-an-internal-or-external-command/)
> perhaps the error was C:\Users\test\AppData\Local\Programs\Python\Python37\Scripts\pivotnacci not pivotnacci.exe as you-get.exe ，if you upgreade pivotnacci.exe to pip source it wil good work.
> thank you .

my way to solve this error is use `pyinstaller -F pivotnacci.py ` to get the full exe file of pivotnacci.exe after git clone  rename `pivotnacci` to `pivotnacci.py`,then copy to `C:\Users\test\AppData\Local\Programs\Python\Python37\Scripts`  Environment Variables PATH，or  other PATH it's will work now:
```
C:\Users\test>pivotnacci -h
usage: pivotnacci [-h] [-s addr] [-p port] [--verbose] [--ack-message message]
                  [--password password] [--user-agent user_agent]
                  [--header header] [--proxy [protocol://]host[:port]]
                  [--type type] [--polling-interval milliseconds]
                  [--request-tries number] [--retry-interval milliseconds]
                  url

Socks server for HTTP agents

positional arguments:
  url                   The url of the agent

optional arguments:
  -h, --help            show this help message and exit
  -s addr, --source addr
                        The default listening address (default: 127.0.0.1)
  -p port, --port port  The default listening port (default: 1080)
  --verbose, -v
  --ack-message message, -a message
                        Message returned by the agent web page (default:
                        Server Error 500 (Internal Error))
  --password password   Password to communicate with the agent (default: )
  --user-agent user_agent, -A user_agent
                        The User-Agent header sent to the agent (default:
                        pivotnacci/0.0.1)
  --header header, -H header
                        Send custom header. Specify in the form 'Name: Value'
                        (default: None)
  --proxy [protocol://]host[:port], -x [protocol://]host[:port]
                        Set the HTTP proxy to use.(Environment variables
                        HTTP_PROXY and HTTPS_PROXY are also supported)
                        (default: None)
  --type type, -t type  To specify agent type in case is not automatically
                        detected. Options are ['php', 'jsp', 'aspx'] (default:
                        None)
  --polling-interval milliseconds
                        Interval to poll the agents (for recv operations)
                        (default: 100)
  --request-tries number
                        The number of retries for each request to an agent. To
                        use in case of balanced servers (default: 50)
  --retry-interval milliseconds
                        Interval to retry a failure request (due a balanced
                        server) (default: 100)
```

**Comment by Mr-xn** [comment]
Maybe you can update the pip resource package to provide .exe files for Windows.

**Comment by zer1t0** [comment]
Hi, thank you for the information. I will investigate the issue.

Meanwhile, you can also install pivotnacci in windows from the repo with the following commands:
```
git clone https://github.com/blackarrowsec/pivotnacci.git
cd pivotnacci/
pip3 install -r requirements.txt
```

**Comment by Mr-xn** [comment]
> Hi, thank you for the information. I will investigate the issue.
> 
> Meanwhile, you can also install pivotnacci in windows from the repo with the following commands:
> 
> ```
> git clone https://github.com/blackarrowsec/pivotnacci.git
> cd pivotnacci/
> pip3 install -r requirements.txt
> ```

thanks
