### ISSUE TITLE
Error when trying to connect through https with a self signed certificate

### ISSUE THREAD

**Issue by hamperfait** [blackarrowsec/pivotnacci#5]
Hi, I'm having this issue. I uploaded the page and when I enter it with the browser, it correctly shows a Server Error 500 (Internal Error), but whenever I try to connect through pivotnacci, this is what I get.

```ERROR:__main__:Error in request: SOCKSHTTPSConnectionPool(host='HOST', port=TOMCAT_PORT): Max retries exceeded with url: /PATH/FILE.jsp (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_ske_dhe', 'dh key too small')])")))```

I'm guessing it's because it's a self signed certificate, so pivotnacci (python's socket, probably) doesn't like it?

**Comment by zer1t0** [comment]
Hi, it seems that OpenSSL is rejecting the key length, could you provide the openssl command to generate a certificate with same characteristics as yours in order to to some tests?

**Comment by hamperfait** [comment]
I think I solved it by updating pyopenssl
`sudo python3 -m pip install --ignore-installed pyOpenSSL --upgrade`, but I'm not sure because I tried using different options.
My bad for opening the issue, sorry
