### ISSUE TITLE
i use the phpstudy and the pivotnacci has a problem

### ISSUE THREAD

**Issue by xsshim** [blackarrowsec/pivotnacci#6]
Fatal error: Uncaught Error: Call to undefined function apache_setenv() in E:\phpstudy_pro\WWW\agent.php:5 Stack trace: #0 {main} thrown in E:\phpstudy_pro\WWW\agent.php on line 5

**Comment by xsshim** [comment]
or this problem:

Fatal error: Call to undefined function apache_setenv() in E:\phpstudy_pro\WWW\agent.php on line 5

**Comment by zer1t0** [comment]
Hi,

What version of phpstudy do you use? It is the same in both errors?

Thank you

**Comment by ResidualLaugh** [comment]
Hello, I also encountered this error. I used php-fpm7.0 and Nginx.

**Comment by ResidualLaugh** [comment]
And the function apache_setenv is not on the list of disabled functions.
