### ISSUE TITLE
I tested it on Tomcat8.5(Windows 7) and RDP Disconnected due to network error by Unknown reason

### ISSUE THREAD

**Issue by xsshim** [blackarrowsec/pivotnacci#7]
![图片](https://user-images.githubusercontent.com/24834308/86990815-105b5200-c1d0-11ea-8086-5d772ecf4b3e.png)

**Comment by zer1t0** [comment]
Hi, 

It only fails with RDP?  Do you have tested it with another protocols that use SSL? 

Thank you
